FROM php:8.1-apache

RUN docker-php-ext-install mysqli pdo pdo_mysql

RUN a2enmod rewrite headers

COPY backend/ /var/www/html/backend/

RUN chown -R www-data:www-data /var/www/html/backend

EXPOSE 80
